version: '3.8'

services:
  redis:
    image: redis:7
    container_name: block_tournament_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: block_tournament_backend
    restart: unless-stopped
    env_file: ./.env.backend
    environment:
      PORT: 4000
      REDIS_URL:
      TELEGRAM_BOT_TOKEN:
      ALLOWED_ORIGINS:
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: block_tournament_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  redisdata:
